### ISSUE TITLE
Project Loading causing crashes.

### ISSUE THREAD

**Issue by PixelRifts** [ambrosiogabe/CDungeonCrawler#3]
I created a Test Project and then I closed the engine. But cannot reopen it. The Engine crashes instantly at AssetManager line 126.
Error I received was:
`Assertion failed: m_value.object->find(key) != m_value.object->end(), file C:\DEV\CDungeonCrawler\JadeEngine\vendor\nlohmann-json\single_include\nlohmann\json.hpp, line 20118`

**Comment by ambrosiogabe** [comment]
Could you let me know which commit you currently have pulled? If it's the latest commit then it's definitely in a broken state. I started to reactor a large portion of the code, and have changed about 1000 lines so far. I got it to compile with no errors and then pushed because I was afraid I would break it even more

**Comment by PixelRifts** [comment]
Latest :D ok then.

**Comment by ambrosiogabe** [comment]
Thanks for logging it though, it will be nice to start tracking bugs formally (instead of the txt file I've been using lol) 👍

**Comment by PixelRifts** [comment]
👍
