### ISSUE TITLE
Unable to clone Cocoa submodules fsr

### ISSUE THREAD

**Issue by PixelRifts** [ambrosiogabe/CDungeonCrawler#9]
I tried to clone the engine to a folder today and i got this in the glfw and box2dvendor submodules.
![image](https://user-images.githubusercontent.com/49561525/108171518-a1f54f80-7121-11eb-8171-41bf03947c84.png)
All the other folders have actual files in them.
And when I run the build script i get this
![image](https://user-images.githubusercontent.com/49561525/108171645-d406b180-7121-11eb-819a-5dbe6a4a9df1.png)

**Comment by ambrosiogabe** [comment]
Thanks for letting me know Nikhil! I must have messed something up when I renamed the project from Jade to Cocoa with the submodules. I'll try and investigate and resolve this by the end of today, or end of tomorrow at the latest 👍

**Comment by ambrosiogabe** [comment]
Hey Nikhil, I just did a fresh clone of the repository and didn't have any problems cloning everything. I might have broken it if you're updating the old repository, but if you do a fresh clone and build it should be good. I also added another step to building FreeType, because I haven't added automatic support for that _yet_. If you could let me know if you're able to build a fresh clone of the repository that would be great :)

Also, the clone time should be much quicker because I dropped PhysX since I'm not using that yet haha

**Comment by PixelRifts** [comment]
OK Thanks

**Comment by PixelRifts** [comment]
Well I cloned it again and it works now. IDK why it did not work before....
